server:
  port: 8082

#数据库配置 spring:
### spring配置
spring:
  datasource:
 #   url: jdbc:mysql://106.55.23.191:3306/timo?serverTimezone=GMT&useSSL=true&autoReconnect=true
    url: jdbc:mysql://106.55.23.191:3306/timo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ABCabc123!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 设置类型为 DruidDataSource

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # mapper文件所在文件夹
  type-aliases-package: com.baron.vo # 别名类(实体类)所在包
  configuration.map-underscore-to-camel-case: true # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId

  # Druid 自定义配置，对应 DruidDataSource 中的 setting 方法的属性
  druid:
    min-idle: 0 # 池中维护的最小空闲连接数，默认为 0 个。
    max-active: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 8 个。
    filter:
      stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
        log-slow-sql: true # 开启慢查询记录
        slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
    stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
      enabled: true # 是否开启 StatViewServlet
      login-username: baron # 账号
      login-password: baron # 密码
